### ISSUE TITLE
页面错乱

### ISSUE THREAD

**Issue by Chen-keeplearn** [winlee28/Jetpack-WanAndroid#1]
大佬你好，提个issue
       看到你在公众号上面发布的，然后刚刚clone下来学习学习，还没看代码，然后运行在手机上，操作了下，发现了页面错乱的问题。错乱截图就先不上传了，我描述下我的操作：就是底部的tab来回的相互切换，多次切换后，按系统的返回键，就会出现

**Comment by winlee28** [comment]
嗯 项目还没有处理  navitation 返回键相关的逻辑  在onBackPressed 中处理就好   后面补上 
因为navitation也是有回退栈的 。

**Comment by Chen-keeplearn** [comment]
嗯嗯，好的

**Comment by winlee28** [comment]
代码已提交
