### ISSUE TITLE
登录逻辑

### ISSUE THREAD

**Issue by Chen-keeplearn** [winlee28/Jetpack-WanAndroid#4]
大佬就是大佬呀，这个时间点依然在工作学习，要成为大佬，果然是需要努力的。这种小问题都不好意思提出来，只是想借此机会向大佬交流学习下。登录之后，再次点击账号昵称，依然要跳转登录页面，顺便说下，登录输入帐号的时候，回车换行了...

主要是想问下大佬：用协程网络请求时，都是会通过BaseRepository中safeApiCall函数转换成NetResult<T>类型是吧？NetResult密封类这样作为返回结果，感觉像是google sample里面的写法，没sample时没看到协程+网络请求这样的处理，所以想学习下这方面的做法

**Comment by winlee28** [comment]
登录问题已改
通过sealed class来包装response 的成功还是失败 给调用方处理

**Comment by winlee28** [comment]
登录问题已改
通过sealed class来包装response 的成功还是失败 给调用方处理

**Comment by winlee28** [comment]
而且所有viemodel中的处理网络返回逻辑可以在一步进行处理 使用扩展函数封装 后可以统一调用

**Comment by Chen-keeplearn** [comment]
好的，谢谢
