### ISSUE TITLE
对于Arouter组件化开发，有个疑惑，想跟大佬交流下，请看详情，谢谢

### ISSUE THREAD

**Issue by Dora0512** [winlee28/Jetpack-WanAndroid#6]
在lib-base里面依赖aroutreApi，在其他模块依赖于lib-base后有需要Arouter时，个人感觉不需要再依赖aroutreApi，只要引入arouterCompiler插件就可以。个人的看法，不知道有没有问题，望一起交流下，谢谢

**Comment by winlee28** [comment]
原则上是可以的 但是每个模块还是需要配置 javaCompileOptions （其实自己动手试试才能印象深刻，学到更多）
项目中是使用compileOnly 占位编译的 ，不会进行打包。
 打包后 也只有主工程中才有相关配置
